# Generated by Django 4.1.5 on 2023-02-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("about", models.TextField(default="No description", max_length=255)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        default="cover4.jpg",
                        null=True,
                        upload_to="Cover_picture",
                    ),
                ),
                (
                    "pp",
                    models.ImageField(
                        blank=True,
                        default="cover2.jpg",
                        null=True,
                        upload_to="Profile_picture",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "connections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
