# Generated by Django 4.1.5 on 2023-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="access_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
