# Generated by Django 4.1.5 on 2023-03-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_profile_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="access_token",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
