# Generated by Django 4.1.5 on 2023-06-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="access_token",
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_post",
                    models.ImageField(blank=True, null=True, upload_to="Posts Images"),
                ),
                ("text_post", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to="main.profile"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_owner",
                        to="main.profile",
                    ),
                ),
            ],
        ),
    ]
