# Generated by Django 4.1.5 on 2023-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_profile_access_token_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="access_token",
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
