# Generated by Django 4.1.5 on 2023-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_post_options_post_created_post_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
