# Generated by Django 4.1.5 on 2023-06-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_post_created_alter_post_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
    ]
