# Generated by Django 4.1.5 on 2023-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_profile_created_remove_profile_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default="2023-06-11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(auto_now_add=True, default="2023-06-11"),
            preserve_default=False,
        ),
    ]
