# Generated by Django 4.1.5 on 2023-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_profile_created_profile_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateTimeField(default="2023-06-11"),
        ),
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(default="2023-06-11"),
        ),
    ]
