# Generated by Django 4.1.5 on 2023-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_post_options_friendrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequests",
            name="status",
            field=models.CharField(
                choices=[("send", "send"), ("accept", "accept")], max_length=30
            ),
        ),
    ]
