# Generated by Django 4.2.2 on 2023-07-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_photo",
                    models.ImageField(blank=True, null=True, upload_to="LifeBook"),
                ),
                ("plan", models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
