# Generated by Django 4.2.2 on 2023-07-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_plan_fiveyear_remove_plan_fiveyearedt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="oneMonthEdt",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="oneMonthSdt",
            field=models.DateField(),
        ),
    ]
