# Generated by Django 4.2.2 on 2023-07-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_threeyearplan_sixmonthplan_oneyearplan_fiveyearplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="threeyearplan",
            old_name="tenYearEdt",
            new_name="threeYearEdt",
        ),
        migrations.RenameField(
            model_name="threeyearplan",
            old_name="tenYearSdt",
            new_name="threeYearSdt",
        ),
        migrations.RenameField(
            model_name="threeyearplan",
            old_name="tenyear",
            new_name="threeyear",
        ),
        migrations.AlterField(
            model_name="threeyearplan",
            name="current_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_LP3y",
                to="main.lifebook",
            ),
        ),
        migrations.AlterField(
            model_name="threeyearplan",
            name="prof",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prof_user3y",
                to="main.profile",
            ),
        ),
        migrations.CreateModel(
            name="TenYearPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenyear", models.BooleanField()),
                ("tenYearSdt", models.DateField()),
                ("tenYearEdt", models.DateField()),
                (
                    "current_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_LP10y",
                        to="main.lifebook",
                    ),
                ),
                (
                    "prof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prof_user10y",
                        to="main.profile",
                    ),
                ),
            ],
        ),
    ]
