# Generated by Django 4.2.2 on 2023-07-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_rename_tenyearedt_threeyearplan_threeyearedt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vision6Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/6month")),
                ("feeling", models.TextField()),
                (
                    "six_month_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sixmonthvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vision5Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/5year")),
                ("feeling", models.TextField()),
                (
                    "five_year_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiveyearvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vision3Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/3year")),
                ("feeling", models.TextField()),
                (
                    "three_year_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threeyearvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vision1Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/1year")),
                ("feeling", models.TextField()),
                (
                    "one_year_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oneyearvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vision1Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/1month")),
                ("feeling", models.TextField()),
                (
                    "one_month_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onemonthvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vision10Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_goal", models.TextField()),
                ("goal_photo", models.ImageField(upload_to="vision/10year")),
                ("feeling", models.TextField()),
                (
                    "ten_year_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenyearvision",
                        to="main.plan",
                    ),
                ),
            ],
        ),
    ]
