# Generated by Django 4.2.2 on 2023-07-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_vision6month_vision5year_vision3year_vision1year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vision10year",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ten_year_name",
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="vision1month",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="one_name",
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="vision1year",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="one_year_name",
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="vision3year",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="three_year_name",
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="vision5year",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="five_year_name",
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="vision6month",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="six_name",
                to="main.profile",
            ),
        ),
    ]
