# Generated by Django 4.2.2 on 2023-07-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_vision10year_ten_year_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Meditation", "Meditation"),
                            ("Fitness", "Fitness"),
                            ("Psychology", "Psychology"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                ("add_choice", models.CharField(blank=True, max_length=250, null=True)),
                ("is_custom_choice", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_choice_person",
                        to="main.profile",
                    ),
                ),
            ],
        ),
    ]
