# Generated by Django 4.2.2 on 2023-07-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_areaofinterest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="areaofinterest",
            name="suggestion",
        ),
    ]
